module.exports = {
	POLLINGRATE: 1000,
	POLLINGRATE_SOURCES: 10000,
	RECONNECT_TIME: 30000,
	DEVICE: undefined,

	CHOICES_OUTPUTS: [{ id: '1', label: 'Output 1' }],
	CHOICES_POSITIONS: [{ id: 1, label: 'Position 1' }],
	CHOICES_POSITIONS_BY_OUTPUT: { '1': [{ id: 1, label: 'Position 1' }] },
	CHOICES_OUTPUT_POSITIONS: [{ id: '1:1', label: 'Output 1 - Position 1' }],
	CHOICES_STREAMS_BY_GROUP: {},
	CHOICES_OUTPUT_LAYOUTS: [{ id: '1:1', label: 'Output 1 - Single' }],
	CHOICES_LAYOUTS: [{ id: 1, label: 'Single' }],
	CHOICES_STREAMS: [{ id: 'null', label: '- No streams available -' }],
	CHOICES_GROUPS: [{ id: 'null', label: '- No groups available -' }],
	CHOICES_SOURCE_TYPES: [
		{ id: 'rtsp', label: 'RTSP' },
		{ id: 'rtmp', label: 'RTMP' },
		{ id: 'rtmps', label: 'RTMPS' },
		{ id: 'http', label: 'HTTP' },
		{ id: 'https', label: 'HTTPS' },
		{ id: 'udp', label: 'UDP' },
	],
	CHOICES_RESOLUTIONS: [{ id: '1', label: '1920x1080P60' }],
	CHOICES_PREVIEW_SLOTS: [{ id: 1, label: 'Preview 1' }],
	CHOICES_VIDEO_INTERFACES: [
		{ id: '1', label: 'HDMI 1' },
		{ id: '2', label: 'HDMI 2' },
		{ id: '3', label: 'SDI' },
	],
	CHOICES_AUDIO_INTERFACES: [
		{ id: '1', label: 'HDMI 1' },
		{ id: '2', label: 'HDMI 2' },
		{ id: '3', label: 'SDI' },
		{ id: '4', label: 'Line Out' },
	],
	CHOICES_OUTPUT_VIDEO_INTERFACES: [{ id: '1:1', label: 'Output 1 - HDMI 1' }],
	CHOICES_OUTPUT_AUDIO_INTERFACES: [{ id: '1:1', label: 'Output 1 - HDMI 1' }],
	CHOICES_VIDEO_INTERFACE_MODES: [
		{ id: 'HDMI', label: 'HDMI' },
		{ id: 'DVI', label: 'DVI' },
	],
	CHOICES_VIDEO_COLORSPACES: [
		{ id: 'RGB444', label: 'RGB444' },
		{ id: 'YCBCR444', label: 'YCBCR444' },
		{ id: 'YCBCR422', label: 'YCBCR422' },
		{ id: 'YCBCR420', label: 'YCBCR420' },
	],
	CHOICES_PTZ_PRESETS: Array.from({ length: 100 }, (_, i) => ({
		id: String(i),
		label: `Preset ${i}`,
	})),

	CHOICES_AUDIOMIX_TYPES: [
		{ id: 'output', label: 'Output Mix' },
		{ id: 'preview', label: 'Preview Mix' },
	],

	STREAM_STATUS_LABELS: {
		0: 'Not Connected',
		1: 'Connecting',
		2: 'Connected',
		3: 'Failed',
		4: 'Performance Limited',
	},

	STATE: {
		device_name: '',
		firmware_version: '',
		hardware_version: '',
		serial_number: '',
		software_version: '',
		outputs: [],
		layouts: [],
		sources: [],
		source_groups: [],
		preview: [],
		audiomix: {},
		video_interfaces: {},
		audio_interfaces: {},
	},

	INTERVAL: null,
	INTERVAL_SOURCES: null,
	RECONNECT_INTERVAL: null,
}
